before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd/vault-context/main.go
    ldflags:
      - -s
      - -w
      - -X github.com/itscontained/vault-context/internal/commands.version={{.Version}}
      - -X github.com/itscontained/vault-context/internal/commands.commit={{.Commit}}
      - -X github.com/itscontained/vault-context/internal/commands.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
